borrower_address = ""
credit_score = ""
criteria_commitment = ""
data_timestamp = ""
is_approved = ""
loan_id = ""
max_dti_percent = ""
max_lti_ratio = ""
min_credit_score = ""
min_data_timestamp = ""
min_income = ""
monthly_debt_payments = ""
monthly_income = ""
nullifier_hash = ""
oracle_public_key_x = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
oracle_public_key_y = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
oracle_signature = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
requested_loan_amount = ""
secret_nullifier_key = ""
